account:
  name: eunsukko

woowahan:
  experimentation:
    client:
      connectTimeout: 5
      socketTimeout: 5
      maxConnTotal: 20
      maxConnPerRoute: 20
      maxIdleTime: 55000
    variation:
      baseUrl: https://experiment-variant.betabaemin.in
      circuitbreaker-enabled: true
    circuitbreaker:
      # connectTimeout, socketTimeout 에 맞게 조정하자
      slowCallDurationThreshold: 5
      slidingWindowSize: 100
      minimumNumberOfCalls: 3
      permittedNumberOfCallsInHalfOpenState: 3
      # OPEN에서 HALF_OPEN으로 상태변이가 실행되는 최소 대기 시간(기본값 1분 -> 60000)
      waitDurationInOpenState: 6000
